services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    restart: unless-stopped
    network_mode: host

  prometheus:
    image: prom/prometheus:v3.4.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerts:/etc/prometheus/alerts:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    network_mode: host

  loki:
    image: grafana/loki:3.4.2
    command: ["-config.file=/etc/loki/loki-config.yaml"]
    volumes:
      - ./loki.yaml:/etc/loki/loki-config.yaml:ro
    restart: unless-stopped
    network_mode: host

  promtail:
    image: grafana/promtail:3.4.2
    command: ["-config.file=/etc/promtail/promtail.yaml"]
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml:ro
      - /var/log/hlprivateer:/var/log/hlprivateer:ro
    restart: unless-stopped
    network_mode: host

  grafana:
    image: grafana/grafana:11.6.0
    volumes:
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/all.yaml:ro
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/hlp:ro
    restart: unless-stopped
    network_mode: host
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
